import streamlit as st

@st.cache_data(ttl=86400)
def get_all_bist_tickers():
    custom_added = [
        "A1CAP.IS", "A1YEN.IS", "ACSEL.IS", "ADEL.IS", "ADESE.IS", "ADGYO.IS", "AEFES.IS", "AFYON.IS",
        "AGESA.IS", "AGHOL.IS", "AGROT.IS", "AGYO.IS", "AHGAZ.IS", "AHSGY.IS", "AKBNK.IS", "AKCNS.IS",
        "AKENR.IS", "AKFGY.IS", "AKFIS.IS", "AKFYE.IS", "AKGRT.IS", "AKMGY.IS", "AKSA.IS", "AKSEN.IS",
        "AKSGY.IS", "AKSUE.IS", "AKYHO.IS", "ALARK.IS", "ALBRK.IS", "ALCAR.IS", "ALCTL.IS", "ALFAS.IS",
        "ALGYO.IS", "ALKA.IS", "ALKIM.IS", "ALKLC.IS", "ALTINS1.IS", "ALTNY.IS", "ALVES.IS", "ANELE.IS",
        "ANGEN.IS", "ANHYT.IS", "ANSGR.IS", "ARASE.IS", "ARCLK.IS", "ARDYZ.IS", "ARENA.IS", "ARMGD.IS",
        "ARSAN.IS", "ARTMS.IS", "ARZUM.IS", "ASELS.IS", "ASGYO.IS"
    ]

    # Daha önce eklediğimiz F'ye kadar olan hisseler
    updated_part = [
        "ASTOR.IS", "ASUZU.IS", "ATAGY.IS", "ATAKP.IS", "ATATP.IS", "ATEKS.IS", "ATLAS.IS", "ATSYH.IS",
        "AVGYO.IS", "AVHOL.IS", "AVOD.IS", "AVPGY.IS", "AVTUR.IS", "AYCES.IS", "AYDEM.IS", "AYEN.IS",
        "AYES.IS", "AYGAZ.IS", "AZTEK.IS", "BAGFS.IS", "BAHKM.IS", "BAKAB.IS", "BALAT.IS", "BALSU.IS",
        "BANVT.IS", "BARMA.IS", "BASCM.IS", "BASGZ.IS", "BAYRK.IS", "BEGYO.IS", "BERA.IS", "BEYAZ.IS",
        "BFREN.IS", "BFRENB.IS", "BIENY.IS", "BIGCH.IS", "BIGEN.IS", "BIMAS.IS", "BINBN.IS", "BINHO.IS",
        "BIOEN.IS", "BIZIM.IS", "BJKAS.IS", "BLCYT.IS", "BMSCH.IS", "BMSTL.IS", "BNTAS.IS", "BOBET.IS",
        "BORLS.IS", "BORSK.IS", "BOSSA.IS", "BRISA.IS", "BRKO.IS", "BRKSN.IS", "BRKVY.IS", "BRLSM.IS",
        "BRMEN.IS", "BRSAN.IS", "BRYAT.IS", "BSOKE.IS", "BTCIM.IS", "BUCIM.IS", "BULGS.IS", "BURCE.IS",
        "BURVA.IS", "BVSAN.IS", "BYDNR.IS", "CANTE.IS", "CASA.IS", "CATES.IS", "CCOLA.IS", "CELHA.IS",
        "CEMAS.IS", "CEMTS.IS", "CEMZY.IS", "CEOEM.IS", "CGCAM.IS", "CIMSA.IS", "CLEBI.IS", "CMBTN.IS",
        "CMENT.IS", "CONSE.IS", "COSMO.IS", "CRDFA.IS", "CRFSA.IS", "CUSAN.IS", "CVKMD.IS", "CWENE.IS",
        "DAGHL.IS", "DAGI.IS", "DAPGM.IS", "DARDL.IS", "DCTTR.IS", "DENGE.IS", "DERHL.IS", "DERIM.IS",
        "DESA.IS", "DESPC.IS", "DEVA.IS", "DGATE.IS", "DGGYO.IS", "DGNMO.IS", "DIRIT.IS", "DITAS.IS",
        "DMRGD.IS", "DMSAS.IS", "DNISI.IS", "DOAS.IS", "DOBUR.IS", "DOCO.IS", "DOFER.IS", "DOGUB.IS",
        "DOHOL.IS", "DOKTA.IS", "DSTKF.IS", "DURDO.IS", "DURKN.IS", "DYOBY.IS", "DZGYO.IS", "EBEBK.IS",
        "ECILC.IS", "ECZYT.IS", "EDATA.IS", "EDIP.IS", "EFORC.IS", "EGEEN.IS", "EGEGY.IS", "EGEPO.IS",
        "EGGUB.IS", "EGPRO.IS", "EGSER.IS", "EKGYO.IS", "EKIZ.IS", "EKOS.IS", "EKSUN.IS", "ELITE.IS",
        "EMKEL.IS", "EMNIS.IS", "ENDAE.IS", "ENERY.IS", "ENJSA.IS", "ENKAI.IS", "ENSRI.IS", "ENTRA.IS",
        "EPLAS.IS", "ERBOS.IS", "ERCB.IS", "EREGL.IS", "ERSU.IS", "ESCAR.IS", "ESCOM.IS", "ESEN.IS",
        "ETILR.IS", "ETYAT.IS", "EUHOL.IS", "EUKYO.IS", "EUPWR.IS", "EUREN.IS", "EUYO.IS", "EYGYO.IS"
    ]

    # Eski listenin geri kalan kısmı (F'den itibaren ve halka arzlar dahil)
    rest_part = [
        "FADE.IS", "FENER.IS", "FONET.IS", "FORMT.IS", "FROTO.IS", "GARFA.IS", "GEDIK.IS", "GEDZA.IS", "GENTS.IS",
        "GENIL.IS", "GEREL.IS", "GESAN.IS", "GIPTA.IS", "GLBMD.IS", "GLCVY.IS", "GOLTS.IS", "GOZDE.IS", "GRNYO.IS",
        "GSDDE.IS", "GSDHO.IS", "GUBRF.IS", "GWIND.IS", "HATEK.IS", "HEKTS.IS", "HDFGS.IS", "HKTM.IS", "HLGYO.IS",
        "HUBVC.IS", "ICBCT.IS", "IDEAS.IS", "IEYHO.IS", "IHLAS.IS", "IHLGM.IS", "IHYAY.IS", "IMASM.IS", "INDES.IS",
        "INFO.IS", "INGRM.IS", "INTEM.IS", "INVEO.IS", "ISDMR.IS", "ISFIN.IS", "ISGYO.IS", "ISGSY.IS", "ISMEN.IS",
        "ISSEN.IS", "IZFAS.IS", "IZINV.IS", "IZMDC.IS", "IZTAR.IS", "JANTS.IS", "KARSN.IS", "KARYE.IS", "KATMR.IS",
        "KCHOL.IS", "KERVT.IS", "KFEIN.IS", "KLGYO.IS", "KLKIM.IS", "KLSER.IS", "KLMSN.IS", "KMPUR.IS", "KNFRT.IS",
        "KONYA.IS", "KORDS.IS", "KOZAA.IS", "KOZAL.IS", "KRDMD.IS", "KRGYO.IS", "KRONT.IS", "KRSTL.IS", "KRVGD.IS",
        "KUTPO.IS", "LIDFA.IS", "LKMNH.IS", "LUKSK.IS", "MAALT.IS", "MACKO.IS", "MAGEN.IS", "MARKA.IS", "MARTI.IS",
        "MAVI.IS", "MEGAP.IS", "MERCN.IS", "MERKO.IS", "MIPAZ.IS", "MMCAS.IS", "MNDRS.IS", "MNDTR.IS", "MRDIN.IS",
        "MRGYO.IS", "MSCLE.IS", "MSGYO.IS", "NETAS.IS", "NIBAS.IS", "NTHOL.IS", "NTTUR.IS", "NUGYO.IS", "ODAS.IS",
        "OLMIP.IS", "ORCAY.IS", "ORGE.IS", "OTKAR.IS", "OYLUM.IS", "OZKGY.IS", "PAPIL.IS", "PARSN.IS", "PENTA.IS",
        "PETKM.IS", "PGSUS.IS", "PKART.IS", "POLHO.IS", "PRKAB.IS", "PRKME.IS", "PSDTC.IS", "QUAGR.IS", "QNBFB.IS",
        "RAYSG.IS", "RALYH.IS", "RHEAG.IS", "RODRG.IS", "ROYAL.IS", "RTALB.IS", "RUBNS.IS", "RYGYO.IS", "RYSAS.IS",
        "SANEL.IS", "SARKY.IS", "SASA.IS", "SAYAS.IS", "SELEC.IS", "SILVR.IS", "SKBNK.IS", "SKTAS.IS", "SNPAM.IS",
        "SNKRN.IS", "SODA.IS", "SOKM.IS", "SOMTA.IS", "SONME.IS", "SRVGY.IS", "SUNTK.IS", "SUWEN.IS", "TABGD.IS",
        "TATGD.IS", "TAVHL.IS", "TCELL.IS", "THYAO.IS", "TKFEN.IS", "TKNSA.IS", "TMCOM.IS", "TMSN.IS", "TOASO.IS",
        "TOLAS.IS", "TRCAS.IS", "TRGYO.IS", "TRILC.IS", "TTRAK.IS", "TUKAS.IS", "TURSG.IS", "TURSH.IS", "TURPS.IS",
        "TSPOR.IS", "TTRAK.IS", "ULKER.IS", "ULUUN.IS", "ULUSE.IS", "UZERB.IS", "VAKFN.IS", "VBTYZ.IS", "VERUS.IS",
        "VESBE.IS", "VESTL.IS", "VKING.IS", "YAPRK.IS", "YATAS.IS", "YGGYO.IS", "YGYO.IS", "YUNSA.IS", "ZOREN.IS",
        "ZRGYO.IS", "YIGIT.IS"
    ]

    return custom_added + updated_part + rest_part
